# Generated by Django 5.0.4 on 2024-04-25 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatOfTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SkillArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.FileField(upload_to='uploads/')),
                ('profession_title', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CPDItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Formal Learning', 'Formal Learning'), ('Self-directed study', 'Self-directed study'), ('Contributing to the profession', 'Contributing to the profession')], max_length=250)),
                ('hours_logged', models.PositiveIntegerField()),
                ('date_completed', models.DateField()),
                ('cost_of_cpd', models.PositiveIntegerField()),
                ('what_did_you_learn', models.TextField(blank=True, null=True)),
                ('future_dev_notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('format_of_training', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.formatoftraining')),
                ('skills_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.skillarea')),
            ],
        ),
    ]
